version: '3.9'
services:
  db:
    image: mariadb
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_ROOT_USER=root 
      - MARIADB_DATABASE=test
    ports:
      - '3306:3306'
